# Generated by Django 5.0.7 on 2024-07-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anacav_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='code',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
