# Generated by Django 5.0.7 on 2024-07-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anacav_data', '0002_alter_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Condition3',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='condition1',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='condition2',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='in_process',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_condition',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
