# Generated by Django 5.0.7 on 2024-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anacav_data', '0003_alter_test_condition3_alter_test_condition1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Condition3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='condition1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='condition2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='in_process',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_condition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
